### ISSUE TITLE
what does r8faults mean?

### ISSUE THREAD

**Issue by dearlancer** [SideChannelMarvels/JeanGrey#5]

**Comment by dearlancer** [comment]
could you apply a demo to show how to get r8faults,thank you

**Comment by doegox** [comment]
r8faults are faulty ciphertexts collected while injecting a fault in round 8.
See
* https://github.com/SideChannelMarvels/Deadpool/tree/master/wbs_aes_grehack2019/DFAr8
* https://github.com/SideChannelMarvels/Deadpool/tree/master/wbs_aes_plaidctf2013/DFAr8
